name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql, intl, zip
          
      - name: Copy .env.prod
        run: php -r "file_exists('.env.prod') || copy('.env.prod.dist', '.env.prod');"
        
      - name: Install dependencies
        run: |
          cd src
          composer install --prefer-dist --no-progress --no-dev
          
      - name: Create cache directory
        run: |
          cd src
          mkdir -p var/cache
          chmod -R 777 var/cache

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/html
            git pull origin main
            
            # Installation des dépendances de production
            docker compose exec -T php composer install --no-dev --optimize-autoloader
            
            # Nettoyage et création du cache
            docker compose exec -T php rm -rf var/cache/*
            docker compose exec -T php php bin/console cache:warmup --env=prod --no-debug
            
            # Mise à jour de la base de données
            docker compose exec -T php php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
            
            # Nettoyage
            docker system prune -f